### ISSUE TITLE
Conection Error

### ISSUE THREAD

**Issue by YuhsiHu** [isl-org/TanksAndTemples#41]
Thank you for your great work!
I found that these days I  cannot upload point cloud because of connection error. I changed the network and PC but still could not  upload file. Some other researchers cannot, neither. Could  you please check the website if it works?
Thank you for your time!

> <<<<<<<<<
start Lighthouse.ply upload
Exiting due to receiving 502 status code when expecting 204.

**Comment by arknapit** [comment]
Did you manage to upload it in the meanwhile? I tested it, and we also had many successful uploads in the meanwhile.

**Comment by YuhsiHu** [comment]
Recently we can upload the point cloud but on June 27 we cannot click "confirm" because the button is still "please use the uploader" after finishing upload. This happens not just in our team, some other researchers cannot confirm for evaluation neither.

**Comment by YuhsiHu** [comment]
Now it works. Thank you for your help!
