### ISSUE TITLE
ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by bdwsq1996** [isl-org/TanksAndTemples#52]
Hello, in the past week, I have been encountering the above error while uploading results.
During each upload process, this issue will occur after uploading 1 to 3 log files.
I have tried uploading repeatedly, changing servers, and updating the credentials, but I have encountered this problem all the time.
I have occasionally uploaded results before, but I have not encountered this problem. Can you tell me how to solve it

**Comment by arknapit** [comment]
I will look into this, can you write me your tanksandtemples username to: arno.knapitsch@gmail.com.
In the meanwhile, could you try the following please (the credential file expires after ~7 days, just to make sure this is not the case):
1. Make a new submission on: https://www.tanksandtemples.org/submit/
2. download (and overwrite if necessary) the credentials file into the folder you want to make the submission from
3. Run the upload script again.
and then let me know if it worked.
