### ISSUE TITLE
Incorrect alignment after trajectory_alignment?

### ISSUE THREAD

**Issue by hanyucc** [isl-org/TanksAndTemples#53]
I was trying to evaluate the Colmap meshes using the evaluation script for the Truck scene, and I found that the transformed Colmap mesh (`Truck.precision.ply`) is not correctly aligned with the ground truth mesh, and the resulting F1 scores is very low.

![snapshot00](https://github.com/isl-org/TanksAndTemples/assets/22674006/b551d330-bf80-4674-a97d-ad30ada0c8d6)

However, I manually verified that the transformation provided in the `Truck_trans.txt` file is correct, and indeed after removing the line `trajectory_transform = trajectory_alignment(map_file, traj_to_register, gt_traj_col, gt_trans, scene)` and directly using `gt_trans` instead of `trajectory_transform`, the alignment looks correct. 

![snapshot01](https://github.com/isl-org/TanksAndTemples/assets/22674006/7df1a6a4-b778-483d-a5b1-3d298fb63e80)

I'm wondering if this is caused by some issue with the alignment code, or if I'm doing something wrong. Moreover, given that we already have the ground truth transformation from Colmap, why do we still need to perform ICP registration on the point cloud? Thanks!

**Comment by arknapit** [comment]
There can be several reasons for this:

1.  can you check that your setup is running correctly for the demo case, e.g. download the [training-data](https://drive.google.com/open?id=1UoKPiUUsKa0AVHFOrnMRhc5hFngjkE-t), extract it to `../trainingdata/` and then run:
`run run.py --dataset-dir ./trainingdata/Truck --traj-path ./trainingdata/Truck/Truck_COLMAP_SfM.log --ply-path ./trainingdata/Truck/Truck_COLMAP.ply`

You should get about this result:

==============================
evaluation result : Truck
==============================
distance tau : 0.005
precision : 0.6490
recall : 0.7020
f-score : 0.6745
==============================

2. Now point `--traj-path` to your SfM-log file and  & `--ply-path` to your *.ply reconstruction, making sure --dataset-dir ./trainingdata/Truck is still the same and the files in it unchanged

- if this is still producing your misaligned results, you can share the reconstruction with me (send a gdrive link to arno.knapitsch@gmail.com) and I can look into it.

**Comment by hanyucc** [comment]
Thanks for the info! I did just figure out what the issue was. The arguments of the `registration_ransac_based_on_correspondence` function have changed in the latest version of Open3D, so as an attempt to fix the issue, I used the default arguments instead of the ones in the original evaluation code, and this led to the incorrect results. After fixing this, it appears to be working properly
