### ISSUE TITLE
Your username and password didn't match or account might not be verified yet.

### ISSUE THREAD

**Issue by zhoouzhe** [isl-org/TanksAndTemples#59]
Hello, I seem to have encountered an issue with account registration. I did receive an email, but the confirmation link in the email does not have a confirmation button. Here is the link: http://tanksandtemples.org/activate/NTI0MA/6nv-48c4137be27673a10d11/ . May I ask if this is normal? I have been waiting for two days.
The email address I used for application is 22220854000308@hainanu.edu.cn Can you help me check?

**Comment by arknapit** [comment]
you need to wait until our staff is manually confirming your registration, this can take 2-3 days, especially over weekends. 
greetings

**Comment by zhoouzhe** [comment]
thanks，I will close the discussion on this issue
